export default {
  Items: [
    {
      Timezone: "CT",
      Description: "8 Team - Teaser - PRIME 7",
      Wagers: [
        {
          idCustomer: 513243,
          AgentName: "",
          CustName: "",
          Password: "",
          FirstName: "",
          NickName: "",
          Website: "",
          Type: "Teaser",
          TicketNumber: 511349448,
          TotalRisk: 100,
          TotalWin: 700,
          Description: "8 Team - Teaser - PRIME 7",
          TeaserName: "PRIME 7",
          PlacedDate: "2024-03-04T13:59:37.62",
          AllowDelete: false,
          FifteenMinsPost: false,
          ContinueOnPush: true,
          Details: [
            {
              Points: 212.5,
              OddsFormatted: "-115",
              Description: "Memphis Grizzlies/Brooklyn Nets",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T18:40:00",
              Outcome: "Pending",
              Rotation: "501/502",
              WagerType: "L",
              PointsOU: "U",
              Header: "Memphis Grizzlies (20-41) @ Brooklyn Nets (24-36)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Memphis Grizzlies",
              Team1Logo: 56,
              Team1Mascot: "Grizzlies",
              Team2: "Brooklyn Nets",
              Team2Logo: 44,
              Team2Mascot: "Nets",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 217,
              OddsFormatted: "-110",
              Description: "Portland Trail Blazers/Minnesota Timberwolves",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T19:10:00",
              Outcome: "Pending",
              Rotation: "505/506",
              WagerType: "L",
              PointsOU: "U",
              Header: "Portland Trail Blazers (17-42) @ Minnesota Timberwolves (42-19)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Portland Trail Blazers",
              Team1Logo: 66,
              Team1Mascot: "Blazers",
              Team2: "Minnesota Timberwolves",
              Team2Logo: 59,
              Team2Mascot: "T-Wolves",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 247,
              OddsFormatted: "-115",
              Description: "Washington Wizards/Utah Jazz",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:10:00",
              Outcome: "Pending",
              Rotation: "507/508",
              WagerType: "L",
              PointsOU: "U",
              Header: "Washington Wizards (9-51) @ Utah Jazz (27-34)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Washington Wizards",
              Team1Logo: 71,
              Team1Mascot: "Wizards",
              Team2: "Utah Jazz",
              Team2Logo: 70,
              Team2Mascot: "Jazz",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 0,
              OddsFormatted: "-105",
              Description: "Duke",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T18:00:00",
              Outcome: "Pending",
              Rotation: "881",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "#10 Duke (23-6) @ NC State (17-12) (ESPN)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Duke",
              Team1Logo: 240,
              Team1Mascot: "",
              Team2: "NC State",
              Team2Logo: 369,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 1.5,
              OddsFormatted: "-110",
              Description: "Weber St",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:00:00",
              Outcome: "Pending",
              Rotation: "885",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "Weber St (20-10) @ Montana St (13-17) (ESPNU)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Weber St",
              Team1Logo: 504,
              Team1Mascot: "",
              Team2: "Montana St",
              Team2Logo: 348,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: -2.5,
              OddsFormatted: "-110",
              Description: "Montana",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:00:00",
              Outcome: "Pending",
              Rotation: "888",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "Idaho St (12-18) @ Montana (20-10)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Idaho St",
              Team1Logo: 284,
              Team1Mascot: "",
              Team2: "Montana",
              Team2Logo: 347,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: -2,
              OddsFormatted: "-110",
              Description: "E Washington",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:00:00",
              Outcome: "Pending",
              Rotation: "889",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "E Washington (20-10) @ Sacramento St (8-22)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "E Washington",
              Team1Logo: 246,
              Team1Mascot: "",
              Team2: "Sacramento St",
              Team2Logo: 412,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 2,
              OddsFormatted: "-110",
              Description: "N Colorado",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T19:00:00",
              Outcome: "Pending",
              Rotation: "883",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "N Colorado (18-12) @ N Arizona (14-17)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "N Colorado",
              Team1Logo: 376,
              Team1Mascot: "",
              Team2: "N Arizona",
              Team2Logo: 375,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
          ],
          Outcome: "Pending",
          WagerNumber: 1,
          IsFreePlay: false,
          TicketType: "INTERNET",
        },
      ],
    },
    {
      Timezone: "CT",
      Description: "8 Team - Teaser - PRIME 7",
      Wagers: [
        {
          idCustomer: 513243,
          AgentName: "",
          CustName: "",
          Password: "",
          FirstName: "",
          NickName: "",
          Website: "",
          Type: "Teaser",
          TicketNumber: 511349486,
          TotalRisk: 150,
          TotalWin: 1050,
          Description: "8 Team - Teaser - PRIME 7",
          TeaserName: "PRIME 7",
          PlacedDate: "2024-03-04T14:00:06.657",
          AllowDelete: false,
          FifteenMinsPost: false,
          ContinueOnPush: true,
          Details: [
            {
              Points: -3,
              OddsFormatted: "-110",
              Description: "Brooklyn Nets",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T18:40:00",
              Outcome: "Pending",
              Rotation: "502",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "Memphis Grizzlies (20-41) @ Brooklyn Nets (24-36)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Memphis Grizzlies",
              Team1Logo: 56,
              Team1Mascot: "Grizzlies",
              Team2: "Brooklyn Nets",
              Team2Logo: 44,
              Team2Mascot: "Nets",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: -7.5,
              OddsFormatted: "-110",
              Description: "Minnesota Timberwolves",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T19:10:00",
              Outcome: "Pending",
              Rotation: "506",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "Portland Trail Blazers (17-42) @ Minnesota Timberwolves (42-19)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Portland Trail Blazers",
              Team1Logo: 66,
              Team1Mascot: "Blazers",
              Team2: "Minnesota Timberwolves",
              Team2Logo: 59,
              Team2Mascot: "T-Wolves",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 1.5,
              OddsFormatted: "-110",
              Description: "Utah Jazz",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:10:00",
              Outcome: "Pending",
              Rotation: "508",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "Washington Wizards (9-51) @ Utah Jazz (27-34)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Washington Wizards",
              Team1Logo: 71,
              Team1Mascot: "Wizards",
              Team2: "Utah Jazz",
              Team2Logo: 70,
              Team2Mascot: "Jazz",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 212.5,
              OddsFormatted: "-115",
              Description: "Memphis Grizzlies/Brooklyn Nets",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T18:40:00",
              Outcome: "Pending",
              Rotation: "501/502",
              WagerType: "L",
              PointsOU: "U",
              Header: "Memphis Grizzlies (20-41) @ Brooklyn Nets (24-36)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Memphis Grizzlies",
              Team1Logo: 56,
              Team1Mascot: "Grizzlies",
              Team2: "Brooklyn Nets",
              Team2Logo: 44,
              Team2Mascot: "Nets",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 217,
              OddsFormatted: "-110",
              Description: "Portland Trail Blazers/Minnesota Timberwolves",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T19:10:00",
              Outcome: "Pending",
              Rotation: "505/506",
              WagerType: "L",
              PointsOU: "U",
              Header: "Portland Trail Blazers (17-42) @ Minnesota Timberwolves (42-19)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Portland Trail Blazers",
              Team1Logo: 66,
              Team1Mascot: "Blazers",
              Team2: "Minnesota Timberwolves",
              Team2Logo: 59,
              Team2Mascot: "T-Wolves",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 247,
              OddsFormatted: "-115",
              Description: "Washington Wizards/Utah Jazz",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T20:10:00",
              Outcome: "Pending",
              Rotation: "507/508",
              WagerType: "L",
              PointsOU: "U",
              Header: "Washington Wizards (9-51) @ Utah Jazz (27-34)",
              SportType: "Basketball",
              SportSubTypeWeb: "NBA",
              IdLeague: 3,
              LeagueTypeName: "Game",
              LeagueName: "NBA",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Washington Wizards",
              Team1Logo: 71,
              Team1Mascot: "Wizards",
              Team2: "Utah Jazz",
              Team2Logo: 70,
              Team2Mascot: "Jazz",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 0,
              OddsFormatted: "-105",
              Description: "Duke",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T18:00:00",
              Outcome: "Pending",
              Rotation: "881",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "#10 Duke (23-6) @ NC State (17-12) (ESPN)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "Duke",
              Team1Logo: 240,
              Team1Mascot: "",
              Team2: "NC State",
              Team2Logo: 369,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
            {
              Points: 2,
              OddsFormatted: "-110",
              Description: "N Colorado",
              AmountRisk: 0,
              AmountToWin: 0,
              EventdDate: "2024-03-04T19:00:00",
              Outcome: "Pending",
              Rotation: "883",
              WagerType: "S",
              PointsOU: "\u0000",
              Header: "N Colorado (18-12) @ N Arizona (14-17)",
              SportType: "Basketball",
              SportSubTypeWeb: "NCAA Basketball",
              IdLeague: 4,
              LeagueTypeName: "Game",
              LeagueName: "NCAA Basketball",
              ContestDesc: "",
              RegulationNote: "",
              PeriodDescription: "Game",
              Pitcher1Required: false,
              Pitcher2Required: false,
              ListedPitcher1: "",
              ListedPitcher2: "",
              PitcherAdjust: 0,
              AdjustableOddsFlag: false,
              IsFreePlay: false,
              OutcomeCode: "P",
              WinnerId: "",
              Team1: "N Colorado",
              Team1Logo: 376,
              Team1Mascot: "",
              Team2: "N Arizona",
              Team2Logo: 375,
              Team2Mascot: "",
              Team1Score: 0,
              Team2Score: 0,
              PendingType: 0,
            },
          ],
          Outcome: "Pending",
          WagerNumber: 1,
          IsFreePlay: false,
          TicketType: "INTERNET",
        },
      ],
    },
  ],
  Page: 0,
  PageSize: 500,
  TotalItemCount: 0,
};
